### PR TITLE
Address logo and cross-link actions from December meeting

### PR DESCRIPTION
**Pull request by erogluorhan**
This PR implements the following:

- Populates README.md to reflect the information on our home page in the Github repo
- Uses Raijin logos in README and homepage
- Adds UXarray links to homepage and README and adds a section on the webpage called "UXarray" with detailed information
- Adds SEATS project members as collaborators to the team section of the webpage
- Fixes a version conflict issue between Python=3.10 and myst-nb package.

[View docs](https://projectraijingithubio.readthedocs.io/en/december_meeting/) for this PR to see most of the changes. on the webpage.

Since this is the first ever PR with a review cycle, I am adding all the members to the reviewers list.

### CODE REVIEW

**Review by clyne — COMMENTED** [review]
Hi Orhan,

I think all of the information looks complete, but the link to the "UXarray page" is broken.

**Review by brianpm — APPROVED** [review]
Except that link that John noted, everything looks good to me. Thanks, @erogluorhan!

**Comment by erogluorhan** [comment]
> View docs

Thanks John! Since we are using an alias (i.e. "raijin.ucar.edu"), the UXarray link will become accessible after this gets merged to main and is deployed. However, you can check that UXarray page here: https://projectraijingithubio.readthedocs.io/en/december_meeting/uxarray.html

**Review by clyne — APPROVED** [review]
looks great. thanks, orhan.

**Review by brianpm — COMMENTED** [review]
This all looks great to me. One potential recommendation (which should not stop this PR being completed at this time) would be to add links to the various external projects/models/formats (e.g., SCRIP, Exodus, MPAS, etc.). Also if SEATS has a website, a link to them.  (Ah, I see this was already merged, which is great.)

**Pull request merged**
