### PR TITLE
Update README.md and Contact.md with embedded calendar

### LINKED ISSUE #7: Publish coordinates for monthly standing meeting
To facilitate community involvement we need to publish the Google Meets coordinates for our standing meeting. 

Question: if we're encouraging outside participation, should we move to zoom?

### PR DESCRIPTION
**Pull request by jukent**
Closes #7

### CODE REVIEW

**Comment by jukent** [comment]
You can see the calendar here: https://projectraijingithubio--15.org.readthedocs.build/en/15/contributing.html
and here: https://projectraijingithubio--15.org.readthedocs.build/en/15/contact.html

per @clyne 's suggestion I'll add it to the bottom of the home page too

**Comment by jukent** [comment]
@clyne @erogluorhan is going to replace the embedded calendar with a new Raijin calendar that he owns (just because I don't think I should own all of the calendars for projects I'm not very involved in)

**Review by erogluorhan — APPROVED** [review]
Thanks a lot!

**Comment by erogluorhan** [comment]
> @clyne @erogluorhan is going to replace the embedded calendar with a new Raijin calendar that he owns (just because I don't think I should own all of the calendars for projects I'm not very involved in)

Done.

**Pull request merged**
