### PR TITLE
Add github communication chart into the Contact Us page

### PR DESCRIPTION
**Pull request by erogluorhan**
Modifies the Contact Us page as follows to embed the How to Communicate chart:

https://projectraijingithubio--5.org.readthedocs.build/en/5/contact.html

### CODE REVIEW

**Review by clyne — COMMENTED** [review]
Thanks for putting this together, @erogluorhan! 

As an uninitiated user visiting the Contact Us page, I think my reaction to being given the choice of choosing between a simple email link, and navigating the flow chart, I would want to use the simpler email link" :-)

Perhaps changing the text under "Though GitHub" to something like the following would help:

Do you have a bug to report, a new feature that you'd like implemented, a technical question to ask, or want to see what others in the community have previously discussed? Open a GitHub Issue or Discussion:

[UXarray Issues ](https://github.com/UXARRAY/uxarray/issues)
[UXarray Discussions](https://github.com/UXARRAY/uxarray/discussions)
[Project Raijin Issues](https://github.com/NCAR/projectraijin.github.io/issues)
[Project Raijin Discussions](https://github.com/NCAR/projectraijin.github.io/discussions)

Not sure whether you have an "Issue" or a "Discussion", or which repo to post your topic to? Consider the flowchart below, or just shoot us an email and we'll help you out!

**Comment by erogluorhan** [comment]
> Thanks for putting this together, @erogluorhan!
> 
> As an uninitiated user visiting the Contact Us page, I think my reaction to being given the choice of choosing between a simple email link, and navigating the flow chart, I would want to use the simpler email link" :-)
> 
> Perhaps changing the text under "Though GitHub" to something like the following would help:
> 

This is great suggestion, thanks @clyne! I have addressed them, please find the latest RTD build below in the PR checks or the contact us page directly [here](https://projectraijingithubio--5.org.readthedocs.build/en/5/contact.html)

**Review by clyne — APPROVED** [review]
Looks great, Orhan! Thanks for doing this.

**Review by brianpm — APPROVED** [review]
This looks great to me! Thanks, @erogluorhan !!

**Review by zarzycki — APPROVED** [review]
Yep, no issues here -- thanks, Orhan!

**Pull request merged**
